name: masterstudy_app
description: MasterStudy App by Stylemix
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.5+68

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #networking
  http: ^1.1.2
  dio: ^5.3.4

  #stateManagement
  flutter_bloc: ^8.1.3

  #utils
  meta: ^1.1.6
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  share_plus: ^7.2.1
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  overlay_support: ^2.1.0
  intl: ^0.18.1


  #googleSignIn
  google_sign_in: ^6.0.2

  #facebookSignIn
  flutter_facebook_auth: ^6.0.3

  #flutter_local_notifications
  flutter_local_notifications: ^15.1.1

  #utils
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  webview_flutter: ^4.4.2
  webview_cookie_manager: ^2.0.6
  webview_flutter_wkwebview: ^3.0.4
  webview_flutter_android: ^3.9.3
  flutter_inappwebview: ^5.7.2+3
  connectivity_plus: ^5.0.2
  external_path: ^1.0.1
  logger: ^1.3.0
  permission_handler: ^11.0.0
  open_file: ^3.3.2
  envied: ^0.5.2
  easy_localization: ^3.0.3
  easy_localization_loader:
    git: https://github.com/aissat/easy_localization_loader.git


  #video_players
  vimeo_player_flutter: ^0.1.0
  youtube_player_flutter: ^8.1.2
  video_player: ^2.6.1
  chewie: ^1.5.0

  flutter_downloader: ^1.11.6


  #firebase
  firebase_crashlytics: ^3.4.6
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6

  #ui
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  shimmer: 2.0.0
  image_picker: ^0.8.4+11
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_html: 3.0.0-alpha.6
  file_picker: ^5.2.5
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.3.0
  html_unescape: ^2.0.0
  page_transition: ^2.0.9
  in_app_purchase: ^3.0.8
  image: ^3.1.3
  fluttertoast: ^8.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  envied_generator: ^0.5.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/localization/
    - assets/
